# Generated by Django 5.0 on 2023-12-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_alter_products_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img_cat',
            field=models.ImageField(default='category.jpg', upload_to='img_category'),
        ),
    ]
