# Generated by Django 5.0 on 2023-12-23 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_listorders_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imgproduct',
            options={'verbose_name': 'Зображення товарів', 'verbose_name_plural': 'Зображення товарів'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Користувач додаток', 'verbose_name_plural': 'Користувачі додаток'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatar/avatar_crj2ayQ.jpg', upload_to='avatar'),
        ),
        migrations.CreateModel(
            name='Coments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(auto_created=True, verbose_name='Час')),
                ('description', models.TextField(verbose_name='Опис')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.products', verbose_name='Товари')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупець')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
            },
        ),
    ]
