# Generated by Django 5.0 on 2023-12-25 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_alter_imgproduct_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coments',
            options={'verbose_name': 'Коментарі', 'verbose_name_plural': 'Коментарі'},
        ),
        migrations.CreateModel(
            name='NoUserBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_user', models.TextField(verbose_name='ip користувача')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.products', verbose_name='Товари')),
            ],
            options={
                'verbose_name': 'Корзина без користувача',
                'verbose_name_plural': 'Корзина без користувача',
            },
        ),
    ]
