# Generated by Django 5.0 on 2023-12-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_alter_coments_options_nouserbasket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nouserbasket',
            name='ip_user',
            field=models.CharField(max_length=30, verbose_name='ip користувача'),
        ),
    ]
