# Generated by Django 5.0 on 2023-12-26 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_alter_nouserbasket_ip_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoUserBasket',
        ),
    ]
