# Generated by Django 5.0 on 2023-12-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_delete_nouserbasket'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoUserListOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, verbose_name='Час')),
                ('name', models.CharField(max_length=100, verbose_name='ФІО')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('address', models.TextField(verbose_name='Адреса')),
                ('description', models.TextField(verbose_name='Замовлення')),
                ('status', models.PositiveIntegerField(default=1, verbose_name='Статус')),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Ціна замовлення')),
            ],
            options={
                'verbose_name': 'Замовлення в один клік',
                'verbose_name_plural': 'Замовлення в один клік',
            },
        ),
    ]
